### ISSUE TITLE
Obtaining the internal ID

### ISSUE THREAD

**Issue by ghost** [bovarysme/memories#2]
Hello, thank you for making this project. I wondered if you could clarify the method for obtaining one's own and chat partners' MIDs (I understand that it is possible to obtain it from the SQLite database on Android, but I don't suppose that's possible without a rooted phone).

**Comment by bovarysme** [comment]
Hello!

I'm afraid I won't be able to give you a precise step-by-step process since I haven't used LINE in a while.
However you could try installing [LINE for Chrome](https://chrome.google.com/webstore/detail/line/ophjlpahpchlmihnnnihgmmeilfjmjjc), use the developer tools (Ctrl+Shift+I) to inspect the page source, then search for elements with a "MID" attribute or strings looking like `u61726520762e206375746520f09f929c`.

I hope this helps.

**Comment by ghost** [comment]
Thank you so much! I was able to find my contacts' IDs each stored as an attribute on the `li` tags that make up the contact list. I recovered my own by creating a group and viewing the list of members, which included myself.

The decryption process was laughably quick, despite running it from a considerably old machine.

Thank you for your efforts. Recovering this chat backup has made me very happy.

**Comment by bovarysme** [comment]
You're more than welcome! Thank you for your kind words. :-)
